---
title: "CDS-abstract-figure"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(patchwork)
library(magick)
library(ggpubr)
```


```{r }

displayA<-ggplot() + background_image(image_read('expt-example-displays/expt-example-displays.001.jpeg'))+coord_fixed() + 
  ggtitle('A') + theme(plot.title=element_text(hjust = 0.15))
displayB<-ggplot() + background_image(image_read('expt-example-displays/expt-example-displays.002.jpeg'))+coord_fixed() + 
  ggtitle('B')+ theme(plot.title=element_text(hjust = 0.15))
displayC<-ggplot() + background_image(image_read('expt-example-displays/expt-example-displays.003.jpeg'))+coord_fixed() + 
  ggtitle('C')+ theme(plot.title=element_text(hjust = 0.15))
displayD<-ggplot() + background_image(image_read('expt-example-displays/expt-example-displays.004.jpeg'))+coord_fixed() + 
  ggtitle('D')+ theme(plot.title=element_text(hjust = 0.15))
displayE<-ggplot() + background_image(image_read('expt-example-displays/expt-example-displays.005.jpeg'))+coord_fixed() + 
  ggtitle('E')+ theme(plot.title=element_text(hjust = 0.15))
  
figA<-read_rds('../group-a/output/exp1_plot.rds')
figB<-read_rds('../group-b/output/ETfig.rds')
figC<-read_rds('../group-c/output/exp3_plot.rds')+scale_color_brewer(palette = "Set1")+
  theme(plot.title=element_text(margin=margin(t=20,b=-15)))
figD<-read_rds('../group-d/output/ETfig.rds')
figE<-read_rds('../group-e/output/exp5_plot.rds')+scale_color_brewer(palette = "Set1")


figA.1<-ggplot(figA$data, 
               aes(x=t.window, y=cumulative.fixation.m, shape = object_class, color = verb_type))+
  geom_point(size=1)+
  geom_line()+
  scale_color_brewer(palette = "Set1", name = "Verb type")+
  scale_shape_manual(name = "Gaze location", values = c(1,4), labels = c("distractor", "target"))+
  theme_classic()+
  labs(x = "Time from Verb Onset", y="Cumulative Look Probability")
figC
```

```{r}
A <- displayA + figA.1 + plot_layout(widths = c(1.5,1)) & theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"))
B <- displayB + figB + plot_layout(widths = c(1.5,1)) & theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"))
C <- displayC + figC + plot_layout(widths = c(1.5,1)) & theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"))
D <- displayD + figD + plot_layout(widths = c(1.5,1)) & theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"))
E <- displayE + figE + plot_layout(widths = c(1.5,1)) & theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"))

```

```{r} 
caption<-"Figure 1. Schematic of trials and key figures for 5 replications attempts. (A) AK99:\nParticipants' cumulative proportion of looks to the target (e.g. cake) and distractor\n(e.g., train) do not differ significantly by verb type. (B) JJ14: When free viewing a\nblank screen during memory retrieval, participants look more to the critical quadrant\nwhere the to-be-remembered object was during encoding. (C) M00: Participants did\nnot look significantly more to the side of the screen with a new image (vs. old).\n(D) ST04: Participants looked least at the target animal and most at the instrument\nwhen the verb was syntactically biased toward an instrument interpretation. (E) S03:\nParticipants' bias to look at the chosen face was not signficantly higher in the\nattractiveness condition (vs. roundness)."

(A | B)/(C | D ) / ( E | (ggpubr::text_grob(caption,
                                            hjust = "left",
                                            vjust = "top",
                                            size = 11)) ) 
```


```{r}
ggsave('CDS-abstract-figure.png', width = 11.5, height = 7)

```

