---
title: "Experiment 5: Calibration Figure"
output: pdf
---

```{r include=FALSE}
library(ggplot2)
library(dplyr)
```

At the beginning of the experimental task, participants completed a
9-point eye-tracker calibration (each point appeared 3 times in random
order) and 3-point validation. The validation point appeared once at
center, middle left, and middle right locations in random order (see Figure\ \@ref(fig:E5-calibration-figure)).
<!-- does 9 points here mean that there were actually only 3 calibration points but each was shown 3 times so 9 total or is it 9 points shown 3 times so 27 total? If the latter, why is the coverage denser than for Experiment 4? -->

```{r include=FALSE}
# calib: [25,25],[25,75],[50,50],[75,25],[75,75],[25,50],[75,50],[15,50],[85,50]
calibration_points <- matrix(c(
  c(25,25),
  c(25,75),
  c(50,50),
  c(75,25),
  c(75,75),
  c(25,50),
  c(75,50),
  c(15,50),
  c(85,50)
), ncol=2, byrow=T)
# valid: 
#      [,1] [,2]
# [1,]   25   50
# [2,]   75   50
# [3,]   50   50
validation_points <- matrix(c(
  c(25,50),
  c(75,50),
  c(50,50)
), ncol=2, byrow=T)

colnames(calibration_points) <- c("x","y")
colnames(validation_points) <- c("x","y")

df <- as_tibble(calibration_points) %>% bind_rows(as_tibble(validation_points))
df$point <- c(rep("calibration", nrow(calibration_points)), rep("validation", nrow(validation_points)))
```

```{r E5-calibration-figure, echo=FALSE, fig.cap="Calibration and validation point locations for Experiment 5. Black points were used for calibration. Red crosses were used for checking the accuracy of the calibration.", fig.width=6, fig.height=4}
ggplot(df, aes(x=x, y=y, shape=point, color=point))+
  geom_point(size=3, stroke=1)+
  scale_shape_manual(values=c(16,3))+
  scale_color_manual(values=c("black", "red"))+
  coord_cartesian(xlim=c(0,100), ylim=c(100,0), expand=FALSE)+
  theme_void()+
  labs(color=NULL, shape=NULL)+
  theme(panel.border = element_rect(color="black", fill=NA),
        legend.position = c(0.995,0.01),
        legend.justification = c(1,0),
        legend.background = element_rect(color="black", fill=NA),
        legend.margin = margin(2,3,3,3))
```