---
title: "E4-analysis-calibration"
author: "Rachel Ryskin"
output: pdf_document
---

```{r , include=FALSE}
library(papaja)
library(jsonlite)
library(dplyr)
library(readr)
library(tidyr)
library(ggplot2)
library(stringr)
library(lmerTest)
library(afex)
library(forcats)
library(broom.mixed)
```


```{r }
data.files <- list.files('data/run-2', full.names = TRUE)
data.tables <- lapply(data.files, function(file){
  data.table <- fromJSON(file)
  return(data.table)
})
all.data <- bind_rows(data.tables)
```


```{r}

all.data.calib = all.data %>% 
  filter(trial_type == "webgazer-validate") %>% 
  dplyr::select(subject, trial_index,  percent_in_roi, average_offset) %>% 
  tidyr::unnest(percent_in_roi)
  
summary.data.calib = all.data.calib %>% 
  group_by(subject, trial_index) %>% 
  summarize(mean_percent_in_roi = mean(percent_in_roi)) %>% 
  group_by(subject) %>% 
  mutate(calib_num = row_number())
```

```{r}
ggplot(summary.data.calib)+
  geom_line(aes(x = calib_num, y = mean_percent_in_roi, color=subject))+
  theme_bw()+
  theme(legend.position = "none") 
```
```{r}
summary.data.calib.wide = summary.data.calib %>% 
  select(-trial_index) %>% 
  pivot_wider(id_cols = subject, names_from=calib_num, values_from = mean_percent_in_roi )

# correlation between initial and halfway calibration
ggplot(summary.data.calib.wide %>% filter(is.na(`3`)), aes(x = `1`, y = `2`))+
  geom_point()+
  geom_smooth(method = 'lm')+
  theme_bw()+
  theme(legend.position = "none") 

# correlation between 2 successive calibration attempts
ggplot(summary.data.calib.wide %>% filter(!is.na(`3`)), aes(x = `1`, y = `2`))+
  geom_point()+
  geom_smooth(method = 'lm')+
  theme_bw()+
  theme(legend.position = "none") 

# correlation between second attempt calibration and halfway
ggplot(summary.data.calib.wide %>% filter(!is.na(`3`)), aes(x = `2`, y = `3`))+
  geom_point()+
  geom_smooth(method = 'lm')+
  theme_bw()+
  theme(legend.position = "none") 
```

```{r}

calib.by.subj = summary.data.calib %>% 
  group_by(subject) %>% 
  summarize(mean_percent_in_roi = mean(mean_percent_in_roi))

eyetracking.effects.by.subj = read_csv( "output/E4_eye-tracking_data.csv") %>% 
  rename("condition" = compatibility) %>% 
  filter(time.window == "post-instrument-onset", condition != "filler" ) %>% 
  group_by(condition, time.window, subject) %>% 
  summarize(M = mean(prop.fixations.animal)) %>% 
  pivot_wider(names_from = condition, values_from = M) %>% 
  mutate(bias_effect = modifier - instrument) %>% 
  left_join(calib.by.subj, by = "subject")
```

```{r}
ggplot(eyetracking.effects.by.subj, aes(x = mean_percent_in_roi, y = modifier))+
  geom_point()+
  geom_smooth(method = "lm")
```

```{r}
ggplot(eyetracking.effects.by.subj, aes(x = mean_percent_in_roi, y = bias_effect))+
  geom_point()+
  geom_smooth(method = "lm")
```
```{r}
eyetracking.window.3 = read_csv( "output/E4_eye-tracking_data.csv") %>% 
  filter(time.window == "post-instrument-onset", compatibility != "filler" ) %>% 
  mutate(condition = factor(compatibility, levels = c('instrument', 'equibiased', 'modifier'))) %>% 
  left_join(calib.by.subj, by = "subject")
```

```{r }
# Add orthogonal contrasts to model
contrasts(eyetracking.window.3$condition) <- cbind(c(-2/3, 1/3, 1/3), c(0, -1/2, 1/2))
```


```{r }

model.time.window.3 <- lmer(prop.fixations.animal ~ condition + (1  | subject) + (1 | trialID), data=eyetracking.window.3,
                            control = lmerControl(optimizer = "bobyqa",
                                                  optCtrl = list(maxfun = 2e6)))
summary(model.time.window.3)
```

```{r}
eyetracking.window.3.good.calib = eyetracking.window.3 %>% 
  filter(mean_percent_in_roi >= 50)
```

```{r }
# Add orthogonal contrasts to model
contrasts(eyetracking.window.3.good.calib$condition) <- cbind(c(-2/3, 1/3, 1/3), c(0, -1/2, 1/2))
```


```{r }

model.time.window.3.good.calib <- lmer(prop.fixations.animal ~ condition + (1  | subject) + (1 | trialID), data=eyetracking.window.3.good.calib,
                            control = lmerControl(optimizer = "bobyqa",
                                                  optCtrl = list(maxfun = 2e6)))
summary(model.time.window.3.good.calib)
```

```{r}
eyetracking.window.3.great.calib = eyetracking.window.3 %>% 
  filter(mean_percent_in_roi >= 75)
```

```{r }
# Add orthogonal contrasts to model
contrasts(eyetracking.window.3.great.calib$condition) <- cbind(c(-2/3, 1/3, 1/3), c(0, -1/2, 1/2))
```


```{r }

model.time.window.3.great.calib <- lmer(prop.fixations.animal ~ condition + (1  | subject) + (1 | trialID), data=eyetracking.window.3.great.calib,
                            control = lmerControl(optimizer = "bobyqa",
                                                  optCtrl = list(maxfun = 2e6)))
summary(model.time.window.3.great.calib)
```