---
title: "Experiment 1: Calibration Figure"
output: pdf
---

```{r include=FALSE}
library(ggplot2)
library(dplyr)
```

```{r include=FALSE}
# calib: 
    # //top
    # [15, 2],
    # [85, 2],
    # //bottom
    # [15, 95],
    # [85, 95],
    # 
    # //inner top
    # [32.5, 26],
    # [67.5, 26],
    # //inner bottom
    # [32.5, 72.5],
    # [67.5, 72.5],
    # 
    # [50, 50]
calibration_points <- matrix(c(
  c(15,2),
  c(85,2),
  c(15,95),
  c(85,95),
  c(32.5,26),
  c(67.5,26),
  c(32.5,72.5),
  c(67.5,72.5),
  c(50,50)
), ncol=2, byrow=T)
# valid: 
#      [,1] [,2]
 # [1,] 15.0  2.0
 # [2,] 85.0  2.0
 # [3,] 15.0 95.0
 # [4,] 85.0 95.0
 # [5,] 22.5 26.0
 # [6,] 67.5 26.0
 # [7,] 22.5 72.5
 # [8,] 67.5 72.5
 # [9,] 50.0 50.0
validation_points <- matrix(c(
  c(15,2),
  c(85,2),
  c(15,95),
  c(85,95),
  c(22.5, 26),
  c(67.5, 26),
  c(22.5, 72.5),
  c(67.5, 72.5),
  c(50,50)
), ncol=2, byrow=T)

colnames(calibration_points) <- c("x","y")
colnames(validation_points) <- c("x","y")

df <- as_tibble(calibration_points) %>% bind_rows(as_tibble(validation_points))
df$point <- c(rep("calibration", nrow(calibration_points)), rep("validation", nrow(validation_points)))
```

```{r echo=FALSE, fig.cap="Calibration and validation point locations for Experiment 1. Black points were used for calibration. Red crosses were used for checking the accuracy of the calibration.", fig.width=6, fig.height=4}
ggplot(df, aes(x=x, y=y, shape=point, color=point))+
  geom_point(size=3, stroke=1)+
  scale_shape_manual(values=c(16,3))+
  scale_color_manual(values=c("black", "red"))+
  coord_cartesian(xlim=c(0,100), ylim=c(100,0), expand=FALSE)+
  theme_void()+
  labs(color=NULL, shape=NULL)+
  theme(panel.border = element_rect(color="black", fill=NA),
        legend.position = c(0.995,0.01),
        legend.justification = c(1,0),
        legend.background = element_rect(color="black", fill=NA),
        legend.margin = margin(2,3,3,3))
```