on:
  push:
    paths: ['**.Rmd']
  workflow_dispatch:

name: render-manuscript

permissions:
  contents: write

jobs:
  render-rmarkdown:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "papaja", "jsonlite", "dplyr", "readr", "tidyr", "ggplot2", "stringr", "lmerTest", "afex", "forcats", "broom.mixed"))'
      - name: Render manuscript
        run: |
          Rscript -e 'rmarkdown::render("manuscript.Rmd")'
      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Render Quarto Manuscript"
          git push origin main
